### ISSUE TITLE
How to use this container with nginx-proxy and letsencrypt-nginx-proxy-companion?

### ISSUE THREAD

**Issue by philrich** [GriffinPlus/docker-zimbra#4]
Hi,

I would like to use your container on a VPS together with other containers and https://github.com/jwilder/nginx-proxy and https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion.

This is my docker-compose.yml for zimbra:
```
---
version: "3"
services:
  zimbra:
    container_name: zimbra
    hostname: ${FQDN}
    build: ./
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_PTRACE
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "5222:5222"
      - "5223:5223"
      - "7071:7071"
    volumes:
      - /opt/appdata/zimbra:/data
    environment:
      - VIRTUAL_HOST=${FQDN}
      - LETSENCRYPT_HOST=${FQDN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    security_opt:
      - apparmor:unconfined
    restart: always
    networks:
      - zimbra
      - webproxy

networks:
  zimbra:
  webproxy:
    external:
      name: webproxy
```

How can I configure the zimbra/nginx-proxy container to work together?

I tried
```
/opt/zimbra/libexec/zmproxyconfig -e -m -w -H ${FQDN} -u
```
to enable HTTP in the zimbra container but it didn't work (redirected me to https://${FQDN}:8443/?zinitmode=http)
